### ISSUE TITLE
Not working on android 5.1 aosp rom

### ISSUE THREAD

**Issue by ghost** [SebiderSushi/sdcard-w_inject#2]
As I mentioned here https://github.com/SebiderSushi/sdcard-w_inject/issues/1#issuecomment-645194452

### Logs
[Android logs.zip](https://github.com/SebiderSushi/sdcard-w_inject/files/4791069/Android.logs.zip)

Im using magisk 20.4

**Comment by SebiderSushi** [comment]
Please refer to the README on what information to include when reporting issues. What you shared seems to include just recovery logs (unrelated) and a Magisk log from a boot where my module was being removed.

Since you say you're running Lollipop, could you also send me the output of `ls -Zahl /system/bin/` in addition to the remaining data as mentionen in the README?

To [my knowledge](https://android.googlesource.com/platform/system/vold/+/refs/heads/lollipop-mr1-release) the `/system/bin/sdcard` binary is not used on Lollipop AOSP and should not even be present. In that case, the approach from this module will not work and i do not intend to make it work as another approach would be necessary, which is out of scope of this particular module.

However, as you stated that your storages did not appear when booting with this module installed i am quite confused since this module shouldn't have that effect in the absence of the `/system/bin/sdcard` binary.

**Comment by ghost** [comment]
Thanks

**Comment by SebiderSushi** [comment]
So does your system not contain a file at `/system/bin/sdcard`?

Because i'm still curious how my module could have had any affect at all on a lollipop device.

**Comment by SebiderSushi** [comment]
On another note: Did you already try the [ExSDCard](https://github.com/Magisk-Modules-Repo/ExSDCard) module on the Magisk Modules repo?

 As far as i know, the method used in that module should work on android Lollipop.

**Comment by SebiderSushi** [comment]
I did some more research and on my OnePlus X, the Lollipop ROMs do, in fact, have an `sdcard` binary, the `-w` option was just [different back then](https://android.googlesource.com/platform/system/core/+/refs/heads/lollipop-mr1-release/sdcard/sdcard.c#1808). I'm just a little puzzled still, since the [vold source code from back then](https://android.googlesource.com/platform/system/vold/+/refs/heads/lollipop-mr1-release) i already linked does not mention the `/system/bin/sdcard` binary in any way.

However, as a consequence, supporting Lollipop could (wasn't able to make it work) be possible with the approach from this module (i.e. by injecting command line options to the `/system/bin/sdcard` binary which would allow the group for apps with storage permission SD Card write access as well). But the cleaner way on Lollipop is definitely to just make sure your storage apps are being added to the `sdcard_rw` group which should be granted sdcard write access by default. And that is already done by said ExSDCard module.
