### ISSUE TITLE
Module does not install

### ISSUE THREAD

**Issue by 1hubber** [SebiderSushi/sdcard-w_inject#4]
Hi,

On my Pixel 5 with ProtonAOSP the Modul does not install.

Magisk shows:
- Copying zip to temp directory
! This zip is not a Magisk Module
! Installation failed

I have the latest version of Magisk:
Magisk: installed version (21102)
Manager: installed version (316)

**Comment by SebiderSushi** [comment]
How did you obtain the zip file? How do the zip file contents look? Please refer to [the release page](https://github.com/SebiderSushi/sdcard-w_inject/releases) for installable versions. Using the `Code` -> `Download ZIP` feature from GitHub does not work as it puts all files into an additional subdirectory within the zip file.

**Comment by 1hubber** [comment]
Thank you, installation of both version was now successful.
However, none of them worked.

I couldn't copy backups (which where created with com.backupyourmobile and TitaniumBackup) from /sdcard or /storage/emulated/0 to my PC
as they where still unreadable bei root.
The files had for example these uid/gid :
-rw------- 1 1023  1023 u:object_r:fuse:s0 	FileName	 
-rw-rw---- 1 10158 1078 u:object_r:media_rw_data_file:s0:c158,c256,c512,c768  FileName

getenforce shows 'enforced' even with "*_permissive.zip"
I can set selinux to 'permissive' with setenforce 0 but still cannot read 

	 	 
But I found out, that root can read/write on "/data/media/0" which is the same as "/sdcard" and "/storage/emulated/0" !
However, it was not possible to download files with "adb pull ..." directly from "/data/media/0" to the PC.

As a workaround I had to copy the files from "/data/media/0" to "/system/bin" (actually I created archives in /system/bin)
From there I could download them to PC with "adb pull ..."

For your information you can find the different uid/gid used in an adb shell below.


# login
adb shell
redfin:/ $ id
uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc),3011(uhid) context=u:r:shell:s0

redfin:/ $ touch /sdcard/empty-sdcard
redfin:/ # ls -Zln /sdcard/empty-sdcard
-rw------- 1 10146 10146 u:object_r:fuse:s0  0 2020-12-25 09:52 /sdcard/empty-sdcard

redfin:/ $ touch /data/media/0/empty-data
touch: '/data/media/0/empty-data': Permission denied


# change to root
redfin:/ $ su
redfin:/ # id
uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0

redfin:/ # touch /sdcard/empty-sdcard-su
redfin:/ # ls -Zln /sdcard/empty-sdcard-su
-rw------- 1 10146 10146 u:object_r:fuse:s0  0 2020-12-25 10:01 /sdcard/empty-sdcard-su

redfin:/ # touch /data/media/0/empty-data-su
redfin:/ # ls -Zln /data/media/0/empty-data-su      
-rw-r--r-- 1 0 0 u:object_r:media_rw_data_file:s0  0 2020-12-25 10:02 /data/media/0/empty-data-su

**Comment by SebiderSushi** [comment]
If the module is incompatible with your ROM then yeah you will not be able to access your files. If you remove the module you should be back to normal. [(mentioned in the readme)](https://github.com/SebiderSushi/sdcard-w_inject#how-to-use-this--troubleshooting)

The `*_permissive.zip` version will not diable all of SELinux but rather turn just the `sdcardd` domain into `permissive` mode, since it is the only one related to this module.  
Turning all of SELinux or parts of it into permissive mode at runtime will not fix your storage because the crucial permissions were already denied while mounting your storage for the first time shortly after booting up. You'd have to take a look at `vold` and on how to trigger it to remount your storage at runtime.  
I found that using a Magisk Module with the command `setenforce 0` in its [`post-fs-data.sh`](https://topjohnwu.github.io/Magisk/guides.html#shell-scripts-sh) can turn SELinux into permissive mode early enough for this module to work. If you are brave enough to try that you can try [this version of my module which turns SELinux permissive completely.](https://github.com/SebiderSushi/sdcard-w_inject/files/5742710/magisk_sdcard-w_inject_1-1.0.0_setenforce0.zip) This module should only be used to gather all necessary logs and to verify that the approach of this module is generally compatible with your ROM.



About the information required to properly debug compatibility with your ROM, please have a look at [the readme](https://github.com/SebiderSushi/sdcard-w_inject#report-issues--incompatibilities).  
The incompatibility that seems most likely to me is that Magisk might be unable to properly inject the SELinux rules on your ROM. If that turns out to be the case, then i don't know anything to do about it. (Except turning off SELinux entirely if you're into that.)

**Comment by SebiderSushi** [comment]
Also please mention the android version you are on. Incompatibility with anything later than android 10 should at least be expected.

**Comment by SebiderSushi** [comment]
As you seem comfortable with root access you might also want to try [the app i made](https://gitlab.com/giwiniswut/android-media-rw-remounter) for the same reason as this module.

**Comment by 1hubber** [comment]
The downloaded zip seems to be ok.

Unzipped files are:

find  -ls
328728824    4 drwxr-xr-x   3 root     root         4096 Dez 24 09:44 .
328728835    8 -rw-r--r--   1 root     root         7352 Dez 24 09:44 ./sdcard-w_inject-master.zip
328728836    4 drwxr-xr-x   4 root     root         4096 Dez 11 00:11 ./sdcard-w_inject-master
328728848    4 drwxr-xr-x   3 root     root         4096 Dez 11 00:11 ./sdcard-w_inject-master/system
328728849    4 drwxr-xr-x   2 root     root         4096 Dez 11 00:11 ./sdcard-w_inject-master/system/bin
328728850    4 -rwxr-xr-x   1 root     root           49 Dez 11 00:11 ./sdcard-w_inject-master/system/bin/sdcard
328728837    4 -rw-r--r--   1 root     root         1073 Dez 11 00:11 ./sdcard-w_inject-master/LICENSE
328728838    4 drwxr-xr-x   3 root     root         4096 Dez 11 00:11 ./sdcard-w_inject-master/META-INF
328728839    4 drwxr-xr-x   3 root     root         4096 Dez 11 00:11 ./sdcard-w_inject-master/META-INF/com
328728840    4 drwxr-xr-x   3 root     root         4096 Dez 11 00:11 ./sdcard-w_inject-master/META-INF/com/google
328728841    4 drwxr-xr-x   2 root     root         4096 Dez 11 00:11 ./sdcard-w_inject-master/META-INF/com/google/android
328728843    4 -rwxr-xr-x   1 root     root            8 Dez 11 00:11 ./sdcard-w_inject-master/META-INF/com/google/android/updater-script
328728842    8 -rwxr-xr-x   1 root     root         4511 Dez 11 00:11 ./sdcard-w_inject-master/META-INF/com/google/android/update-binary
328728844    4 -rw-r--r--   1 root     root         4062 Dez 11 00:11 ./sdcard-w_inject-master/README.md
328728847    4 -rw-r--r--   1 root     root          108 Dez 11 00:11 ./sdcard-w_inject-master/sepolicy.rule
328728846    4 -rwxr-xr-x   1 root     root          659 Dez 11 00:11 ./sdcard-w_inject-master/post-fs-data.sh
328728845    4 -rwxr-xr-x   1 root     root          129 Dez 11 00:11 ./sdcard-w_inject-master/module.prop

**Comment by 1hubber** [comment]
As far as I can see your modules seem to be OK.

I have seen that selinux is already in Permissive state before setenforce 0 is executed in your post-fs-data.sh of magisk_sdcard-w_inject_1-1.0.0_setenforce0.zip. (I added a line to the script to log the output of getenforce )

Therefore I think that Android 11 and/or Magisk are the reason for the permission problems.

Anyway, for your information I have attached the files. (logcat -d | grep sdcard has no result)

[output.zip](https://github.com/SebiderSushi/sdcard-w_inject/files/5744680/output.zip)
